# LAB 1: Write a program to demonstrate the NumPy array and perform functions on it.

## Installing NumPy

In [2]:
! pip install numpy --upgrade

  Attempting uninstall: numpy
    Found existing installation: numpy 1.16.2
    Uninstalling numpy-1.16.2:
      Successfully uninstalled numpy-1.16.2


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tables 3.5.1 requires mock>=2.0, which is not installed.
You should consider upgrading via the 'c:\users\student\anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

# NumPy array creation - 1


In [12]:
a = np.arange(20).reshape(2,2,5) 
print(a)
# arange - start range from 0 to 15
#reshape - shape the number into n-dimension

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


# Attributes of numpy array

In [19]:
# ndim - to check the dimensions of array 
print("Dimension of an array a = ", a.ndim)


#check the shape of array
print("no of colm and rows in array a= ", a.shape)

#check the total no of elements in array
print("Size of array a = ", a.size)

#check the data type of array element
print("Data type of array a = ",a.dtype)

#check item size(each element takes how many bytes of data)
print("Item size of a = ",a.itemsize)

#check the memory location for array
print("Memory location of array a = ", a.data)

Dimension of an array a =  3
no of colm and rows in array a=  (2, 2, 5)
Size of array a =  20
Data type of array a =  int32
Item size of a =  4
Memory location of array a =  <memory at 0x000001CA5CDE5E58>


# Array creation using array()

In [27]:
#1-d array
a = np.array([3,2,1])
print("1-d array ", a)

#2-d array 
a1 = np.array([(1,2,3,4),(5,6,7,8),(1,3,8,0)])
print("\n 2-d array\n " ,a1)


#3-d array
a2 = np.array([[(1,2),(3,4),(5,6),(8,0)]])
print(a2.ndim)

1-d array  [3 2 1]

 2-d array
  [[1 2 3 4]
 [5 6 7 8]
 [1 3 8 0]]
3


# Type conversion in array

In [29]:
#implicit conversion (system decided)

d = np.array([[1,3,5.6],[2,5,9]])
print(d)

[[1.  3.  5.6]
 [2.  5.  9. ]]


In [32]:
#explict conversion(user decided)

d = np.array([[1,3,5.6],[2,5,9]],dtype='str') #int/float/complex
print(d)


[['1' '3' '5.6']
 ['2' '5' '9']]


# Unique or standard array creation in numpy

In [41]:
# zeros array

z=np.zeros((1,2))
print(z)
print(z.data)

[[0. 0.]]


In [42]:
#ones array

z1=np.ones((2,3))
print(z1)
print(z.data)

[[1. 1. 1.]
 [1. 1. 1.]]


In [44]:
#empty array

z2=np.empty((3,3))
print(z2)
print(z.data)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.86921958e-306 1.78020848e-306 1.42418987e-306]
 [1.37961641e-306 1.86906204e-306 1.08225056e-312]]


# NumPy arange()

In [46]:
#arange fuc creates range from lower to upper-step and it will increment as per step, by defalut=1
#np.arrange(lower,upper,step)

l = np.arange(10,110,5)
print(l)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100 105]


In [48]:
#can't predict the no of elements 
m = np.arange(0,2,0.12)
print(m)
print(m.size)

[0.   0.12 0.24 0.36 0.48 0.6  0.72 0.84 0.96 1.08 1.2  1.32 1.44 1.56
 1.68 1.8  1.92]
17


# Linspace() in NumPy

In [52]:
# linspace = (lower, upper, no.of elements)
from math import pi
m= np.linspace(0,10*pi,10)
print(m)

#in linspace -- upper bound included
#in arange -- upper bound neglected

[ 0.          3.4906585   6.98131701 10.47197551 13.96263402 17.45329252
 20.94395102 24.43460953 27.92526803 31.41592654]


# Basic operation on numpy

In [60]:
a = np.array([[20,5],[10,2]])
b = np.array([[2,3],[4,9]])

print(b**2)

[[ 4  9]
 [16 81]]


In [61]:
np.sin(a)

array([[ 0.91294525, -0.95892427],
       [-0.54402111,  0.90929743]])

In [62]:
print(a>7)

[[ True False]
 [ True False]]


In [63]:
print(a*b) #elementwise

[[40 15]
 [40 18]]


In [64]:
print(a@b) #matrixwise

[[ 60 105]
 [ 28  48]]


In [67]:
print(a.dot(b)) #dot product

[[ 60 105]
 [ 28  48]]
