<a href="https://colab.research.google.com/github/sakshipagaria/Data-science-Machine-Learning/blob/main/ML_LAB2_T2_28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 2: Data Preprocessing Tools

## Import Libraries





In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import Dataset

In [2]:
dataset = pd.read_csv("Data.csv")

In [3]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
dataset.shape

(10, 4)

In [5]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [7]:
dataset.describe(include= 'object')

Country Purchased
count       10        10
unique       3         2
top     France        No
freq         4         5

In [8]:
X = dataset.iloc[: , :-1].values
print(X)
Y = dataset.iloc[: , -1].values
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Step 2: Handle the missing values in Dataset

In [9]:
from sklearn.impute import SimpleImputer 
#  steps for sklearn
# imported package
# create object
# fit and transform

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[: , 1:3])
X[: , 1:3] = imputer.transform(X[: , 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Step 3 : encoding the categorical data

**A. Encoding the Independent Variable(i/p feature/X)**

In X we have country as Categorical feature

It has 3 categories

hence used One Hot Encoder

In [10]:
dataset['Country'].value_counts()

France     4
Spain      3
Germany    3
Name: Country, dtype: int64

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct= ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X)) 

In [12]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding the dependent variable(o/p feature Y)

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [14]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


# Step 4: split the dataset into training and testing data

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.3, random_state = 1)

In [16]:
print(X_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [17]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [18]:
print(Y_test)

[0 1 0]


# Step 5:Feature Scaling

Standard scalar

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :3] = sc.fit_transform(X_train[:,:3])
X_test[:, :3] = sc.fit_transform(X_test[:, :3])

In [20]:
print(X_test)

[[-0.7071067811865475 1.4142135623730951 -0.7071067811865475 30.0 54000.0]
 [1.4142135623730951 -0.7071067811865475 -0.7071067811865475 37.0 67000.0]
 [-0.7071067811865475 -0.7071067811865475 1.4142135623730951
  38.77777777777778 52000.0]]


## Task:Test your knowledge 

### Write a code to Feature Scaling our dataset numerical variable using MinMaxScaler

In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train_scale = scaler.fit_transform(X_train[:, 3:])
X_test_scale = scaler.transform(X_test[:, 3:])
X_train[:, 3:] = X_train_scale
X_test[:, 3:] = X_test_scale

In [25]:
print(X_train)
print(X_test)

[[-0.8660254037844387 1.5811388300841895 -0.6324555320336758
  0.5652173913043479 0.45079365079365075]
 [1.1547005383792517 -0.6324555320336758 -0.6324555320336758
  0.7391304347826089 0.6857142857142855]
 [-0.8660254037844387 -0.6324555320336758 1.5811388300841895
  0.4782608695652175 0.37142857142857144]
 [-0.8660254037844387 -0.6324555320336758 1.5811388300841895 0.0 0.0]
 [1.1547005383792517 -0.6324555320336758 -0.6324555320336758
  0.9130434782608696 0.8857142857142857]
 [-0.8660254037844387 1.5811388300841895 -0.6324555320336758 1.0 1.0]
 [1.1547005383792517 -0.6324555320336758 -0.6324555320336758
  0.34782608695652173 0.2857142857142856]]
[[-0.7071067811865475 1.4142135623730951 -0.7071067811865475
  0.1304347826086958 0.17142857142857149]
 [1.4142135623730951 -0.7071067811865475 -0.7071067811865475
  0.43478260869565233 0.5428571428571427]
 [-0.7071067811865475 -0.7071067811865475 1.4142135623730951
  0.5120772946859904 0.11428571428571432]]


### For the below student dataset remove missing values from column ‘gender’ and ‘marks'

In [26]:
students = [[85, 'M', 'verygood'],
 [95, 'F', 'excellent'],
 [75, None, 'good'],
 [np.NaN, 'M', 'average'],
 [70, 'M', 'good'],
 [np.NaN, None, 'verygood'],
 [92, 'F', 'verygood'],
 [98, 'M', 'excellent']]

In [29]:
dfstd = pd.DataFrame(students)
dfstd.columns = ['marks', 'gender', 'result']
dfstd_cleaned = dfstd.dropna(subset=['gender', 'marks'])
print(dfstd_cleaned)

   marks gender     result
0   85.0      M   verygood
1   95.0      F  excellent
4   70.0      M       good
6   92.0      F   verygood
7   98.0      M  excellent


In [30]:
dfstd_encoded = pd.get_dummies(dfstd, columns=['gender', 'result'])

# Print the encoded dataset
print(dfstd_encoded)

   marks  gender_F  gender_M  result_average  result_excellent  result_good  \
0   85.0         0         1               0                 0            0   
1   95.0         1         0               0                 1            0   
2   75.0         0         0               0                 0            1   
3    NaN         0         1               1                 0            0   
4   70.0         0         1               0                 0            1   
5    NaN         0         0               0                 0            0   
6   92.0         1         0               0                 0            0   
7   98.0         0         1               0                 1            0   

   result_verygood  
0                1  
1                0  
2                0  
3                0  
4                0  
5                1  
6                1  
7                0  
