<a href="https://colab.research.google.com/github/sakshipagaria/Data-science-Machine-Learning/blob/main/ML_LAB3B_T2_28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 3B- Multiple Linear Regression

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Importing Dataset

In [2]:
dataset = pd.read_csv("50_Startups.csv")
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

### Finding the Meta Data Informationof Data

In [3]:
dataset.shape

(50, 5)

In [4]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [6]:
dataset.describe(include = 'object')

State
count         50
unique         3
top     New York
freq          17

### Data Preprocessing

In [7]:
x = dataset.iloc[: ,:-1].values   # independent
y = dataset.iloc[: , -1].values   # dependent

In [8]:
print(x)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [9]:
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


### Encoding Categorical feature "State"

In [10]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[3])],remainder ='passthrough')
x = ct.fit_transform(x) 

In [11]:
print(x[0:5])

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


### Spliting the Data into Training and Testing

In [12]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 0 )

In [13]:
print(x_train)

[[0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 0.0 46426.07 157693.92 210797.67]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [1.0 0.0 0.0 63408.86 129219.61 46085.25]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 15505.73 127382.3 35534.17]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [1.

In [14]:
print(x_test)

[[0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]


In [15]:
print(y_train)


[ 96778.92  96479.51 105733.54  96712.8  124266.9  155752.6  132602.65
  64926.08  35673.41 101004.64 129917.04  99937.59  97427.84 126992.93
  71498.49 118474.03  69758.98 152211.77 134307.35 107404.34 156991.12
 125370.37  78239.91  14681.4  191792.06 141585.52  89949.14 108552.04
 156122.51 108733.99  90708.19 111313.02 122776.86 149759.96  81005.76
  49490.75 182901.99 192261.83  42559.73  65200.33]


In [16]:
print(y_test)

[103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]


### Build Multiple Linear regression

In [17]:
# Importing LinearRegression from sklearn 

from sklearn.linear_model import LinearRegression
mreg = LinearRegression()
mreg.fit(x_train,y_train)

LinearRegression()

In [18]:
# Check the attributes of our model

print("Cofficient of Model = " ,mreg.coef_)
print("Intercept of Model = " ,mreg.intercept_)

Cofficient of Model =  [ 8.66383692e+01 -8.72645791e+02  7.86007422e+02  7.73467193e-01
  3.28845975e-02  3.66100259e-02]
Intercept of Model =  42467.52924853278


In [19]:
# Checking Accuracy of model

print("Accuracy of the Model = " , mreg.score(x_train , y_train) )

Accuracy of the Model =  0.9501847627493607


In [20]:
# Predicting Test Data

yhat = mreg.predict(x_test)
print(yhat)


[103015.20159795 132582.27760816 132447.73845175  71976.09851258
 178537.48221057 116161.24230167  67851.69209676  98791.73374687
 113969.43533014 167921.06569552]


In [21]:
print(y_test)
print(yhat)

[103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]
[103015.20159795 132582.27760816 132447.73845175  71976.09851258
 178537.48221057 116161.24230167  67851.69209676  98791.73374687
 113969.43533014 167921.06569552]


In [25]:
# Making the simple prediction ( R&D = 300000 , Administration = 160000 , Marketing = 200000 , State= 'Flroida')

mreg.predict([[1,0,0,300000,160000,200000]])

array([287177.86621613])

### Evaluating a Model using R2 Metric

In [23]:
# Importing the R2 form sklearn

from sklearn.metrics import r2_score
r2_score(y_test,yhat)

0.9347068473282546

# Task:Test your knowledge 

In [27]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 45 )

In [28]:
print(x_train)

[[1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [1.0 0.0 0.0 22177.74 154806.14 28334.72]
 [0.0 1.0 0.0 28663.76 127056.21 201126.82]
 [1.0 0.0 0.0 0.0 116983.8 45173.06]
 [1.0 0.0 0.0 64664.71 139553.16 137962.62]
 [0.0 1.0 0.0 1315.46 115816.21 297114.46]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 1000.23 124153.04 1903.93]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [0.0 1.0 0.0 55493.95 103057.49 214634.81]
 [1.0 0.0 0.0 38558.51 82982.09 174999.3]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 15505.73 127382.3 35534.17]
 [0.0 0.0 1.0 77

In [29]:
print(x_test)

[[1.0 0.0 0.0 0.0 135426.92 0.0]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [1.0 0.0 0.0 44069.95 51283.14 197029.42]
 [0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]]


In [30]:
print(y_train)

[118474.03 124266.9  126992.93  78239.91  65200.33  90708.19  14681.4
 107404.34  49490.75  35673.41  64926.08  77798.83 105008.31 110352.25
 101004.64 146121.95 103282.38  96778.92  81005.76  71498.49 156122.51
 125370.37  69758.98 108552.04  96712.8  141585.52  81229.06 108733.99
 152211.77 132602.65 191792.06 129917.04 166187.94  96479.51 111313.02
  97483.56  97427.84 182901.99  99937.59 144259.4 ]


In [31]:
print(y_test)

[ 42559.73 155752.6  191050.39 149759.96 156991.12 105733.54 134307.35
  89949.14 192261.83 122776.86]


In [33]:
# Importing LinearRegression from sklearn 
from sklearn.linear_model import LinearRegression
tmreg = LinearRegression()
tmreg.fit(x_train,y_train)

LinearRegression()

In [34]:
# Check the attributes of our model
print("Cofficient of Model = " ,tmreg.coef_)
print("Intercept of Model = " ,tmreg.intercept_)

Cofficient of Model =  [ 7.30227687e+01  8.36136010e+01 -1.56636370e+02  7.95919887e-01
 -2.48493625e-02  3.02809102e-02]
Intercept of Model =  49972.912149916694


In [35]:
# Checking Accuracy of model
print("Accuracy of the Model = " , tmreg.score(x_train , y_train) )

Accuracy of the Model =  0.9335592411497009


In [36]:
# Predicting Test Data
tyhat = mreg.predict(x_test)
print(tyhat)

[ 46680.66228471 159954.35005297 182022.90173147 154745.13158053
 163287.16342378 110489.74232995 127548.46548019  89813.96136691
 192305.22120806 114784.70582436]


In [37]:
print(y_test)
print(tyhat)

[ 42559.73 155752.6  191050.39 149759.96 156991.12 105733.54 134307.35
  89949.14 192261.83 122776.86]
[ 46680.66228471 159954.35005297 182022.90173147 154745.13158053
 163287.16342378 110489.74232995 127548.46548019  89813.96136691
 192305.22120806 114784.70582436]


In [38]:
# Making the simple prediction ( R&D = 300000 , Administration = 160000 , Marketing = 200000 , State= 'Flroida')
tmreg.predict([[1,0,0,300000,160000,200000]])

array([290902.18492494])